services:
  mitoga-project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-}
        VERSION: ${VERSION:-0.0.1}
        GIT_COMMIT: ${GIT_COMMIT:-}
        BUILD_NUMBER: ${BUILD_NUMBER:-}
    image: mitoga-project:latest
    container_name: mitoga-project
    restart: unless-stopped
    ports:
      - "8081:8082"
    networks:
      - mitoga-net
networks:
  mitoga-net:
    external: true